name: setup

runs:
  using: "composite"
  steps:
    - name: Setup
      shell: bash
      run: |
        mkdir -v -p ~/.local/share/godot/export_templates/
        mv \
          /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable \
          ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
        mkdir \
          build/windows/ \
          build/linux/ \
          build/android/ \
          build/ios/
