name: "Build"
on: push

env:
  GODOT_VERSION: 4.3
  PROJECT_NAME: project-name

jobs:
  export:
    name: ${{ matrix.platform }}
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.3
    strategy:
      matrix:
        platform:
          - windows
          - linux

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv \
            /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable \
            ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
          mkdir build/${{ matrix.platform }}/

      - name: Build
        run: |
          if [ "${{ matrix.platform }}" == "windows" ]; then
            godot --headless --verbose --export-release "Windows Desktop" ./build/${{ matrix.platform }}/$PROJECT_NAME.exe
          elif [ "${{ matrix.platform }}" == "linux" ]; then
            godot --headless --verbose --export-release "Linux" ./build/${{ matrix.platform }}/$PROJECT_NAME.x86_64
          elif [ "${{ matrix.platform }}" == "android-debug" ]; then
            godot --headless --verbose --export-debug "Android Debug" ./build/android-debug/$PROJECT_NAME-debug.apk
          fi

      - name: Compress
        run: |
          cd build
          tar -cvf $PROJECT_NAME-${{ matrix.platform }}.tar ${{ matrix.platform }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}
          path: build/${{ env.PROJECT_NAME }}-${{ matrix.platform }}.tar
